[terminal]
shell = { program = "wsl", args = ["-d", "Ubuntu", "--cd", "~"] }

[[keyboard.bindings]]
key = "C"
mods = "Control"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
chars = "\u0003"

[window]
opacity = 0.9

# Colors (Aura Theme)
# Default colors
[colors.primary]
background = '#15141b'
foreground = '#edecee'

# Normal colors
[colors.normal]
black   = '#110f18'
red     = '#ff6767'
green   = '#61ffca'
yellow  = '#ffca85'
blue    = '#a277ff'
magenta = '#a277ff'
cyan    = '#61ffca'
white   = '#edecee'

# Bright colors
[colors.bright]
black   = '#4d4d4d'
red     = '#ff6767'
green   = '#61ffca'
yellow  = '#ffca85'
blue    = '#a277ff'
magenta = '#a277ff'
cyan    = '#61ffca'
white   = '#edecee'

[colors.selection]
text       = 'CellForeground'
background = '#29263c'

[colors.cursor]
cursor = '#a277ff'
