[colors.primary]
background = '#291d14'
foreground = '#f3f2f2'
 
[colors.cursor]
text = '#f3f2f2'
cursor = '#b6b2af' 
 
[colors.vi_mode_cursor]
text = '#291d14'
cursor = '#ec9960' 
 
[colors.search.matches]
foreground = '#37261b' 
background = '#a8e949' 
 
[colors.search.focused_match]
foreground = '#37261b' 
background = '#ec9960' 
 
[colors.footer_bar]
foreground = '#37261b' 
background = '#e8e5e3' 
 
[colors.hints.start]
foreground = '#37261b' 
background = '#5597dd' 
 
[colors.hints.end]
foreground = '#37261b' 
background = '#5597dd' 
 
[colors.selection]
text = '#291d14'
background = '#ec9960'
 
 
[colors.normal]
black = '#181818' 
red = '#964812' 
green = '#ec9960' 
yellow = '#a65a26' 
blue = '#ec9960' 
magenta = '#a8e949' 
cyan = '#5597dd' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 